name = "VanillaQOL 1.21"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c167bf0ea3beda96c6b06f8f26eba69abd2c9913c080f184d0f1de862c1607f5"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.20.6"]
