name = "VanillaQOL 1.21"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad4163fc0da612ff45e224a04c74fa90b839a949c14b28e2552d2d0c81942bd9"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.20.6"]
