name = "VanillaQOL 1.21"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b50d811aedca192c40db16aee7651f20ee1a7062f107a4765bc15f8af6602d1"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
