name = "VanillaQOL 1.21"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2abaa2773a16742912c123a30478afe78f42c9a758ab2280bc57c99a002f6c0"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.20.6"]
